name: Keep Backend Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping
        run: |
          curl -s https://ar-learn-backend.onrender.com/health || true
